### ISSUE TITLE
Problema "à" su Excel

### ISSUE THREAD

**Issue by MerrymanLyon** [Sclafus/us_keyboard_with_italian_letters#1]
Ciao,
trovo la tua tastiera perfetta per ogni utilizzo.
Ormai da un paio di mesi ho acquistato una tastiera meccanica con layout US e con la tua tastiera sono sempre stato in grado di lavorare efficientemente.
L'unico problema che ho riscontrato è quando cerco di fare la à in una casella di Excel: ogni volta che faccio la combinazione di tasti (alt gr + a) la cella si cancella di tutto il contenuto e me lo sostituisce solo con la a accentata.
Sai come mai succede questo problema?
Grazie mille!

**Comment by Sclafus** [comment]
Ciao @MerrymanLyon, sembrerebbe un problema di Excel ad occhio, ma provo a riprodurlo!

**Comment by Sclafus** [comment]
Ho appena provato, effettivamente hai ragione.
Non conosco molto bene Excel, ma è possibile che AltGR+A sia effettivamente una hotkey per cancellare la cella/selezionare tutto il testo?
L'unico workaround che mi può venire in mente è usare AltGR+Z per fare la á, e poi sostituirlo con à con una qualche funzione di rimpiazzo caratteri, oppure disabilitare quella hotkey in qualche modo

**Comment by Sclafus** [comment]
Chiudo per inattività
